version: '2'
services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      http_proxy: ${http_proxy}
      no_proxy: ${no_proxy}
  logstash:
    build:
      context: logstash/
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    environment:
      http_proxy: ${http_proxy}
      no_proxy: ${no_proxy}
    ports:
      - "5044:5044"
    links:
      - elasticsearch
  provisioner:
    build:
      context: provisioner/
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    volumes:
      - "./provisioner/initial_import:/initial_import"
    links:
      - elasticsearch
  kibana:
    build:
      context: kibana/
    volumes:
       - "./kibana/config/:/etc/kibana/"
    ports:
       - "5601:5601"
    links:
       - elasticsearch
